// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.31.1
// source: packet.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Observable } from "rxjs";
import { share } from "rxjs/operators";

export const protobufPackage = "packet";

export interface Empty {
}

export interface Packet {
  type: string;
  srcIp: string;
  dstIp: string;
  srcIsAgent: boolean;
  dstIsAgent: boolean;
  size: number;
  proto: string;
  srcPort: number;
  dstPort: number;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBasePacket(): Packet {
  return {
    type: "",
    srcIp: "",
    dstIp: "",
    srcIsAgent: false,
    dstIsAgent: false,
    size: 0,
    proto: "",
    srcPort: 0,
    dstPort: 0,
  };
}

export const Packet: MessageFns<Packet> = {
  encode(message: Packet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.srcIp !== "") {
      writer.uint32(18).string(message.srcIp);
    }
    if (message.dstIp !== "") {
      writer.uint32(26).string(message.dstIp);
    }
    if (message.srcIsAgent !== false) {
      writer.uint32(32).bool(message.srcIsAgent);
    }
    if (message.dstIsAgent !== false) {
      writer.uint32(40).bool(message.dstIsAgent);
    }
    if (message.size !== 0) {
      writer.uint32(48).int32(message.size);
    }
    if (message.proto !== "") {
      writer.uint32(58).string(message.proto);
    }
    if (message.srcPort !== 0) {
      writer.uint32(64).int32(message.srcPort);
    }
    if (message.dstPort !== 0) {
      writer.uint32(72).int32(message.dstPort);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Packet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.srcIp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dstIp = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.srcIsAgent = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dstIsAgent = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.proto = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.srcPort = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.dstPort = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Packet {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      srcIp: isSet(object.srcIp) ? globalThis.String(object.srcIp) : "",
      dstIp: isSet(object.dstIp) ? globalThis.String(object.dstIp) : "",
      srcIsAgent: isSet(object.srcIsAgent) ? globalThis.Boolean(object.srcIsAgent) : false,
      dstIsAgent: isSet(object.dstIsAgent) ? globalThis.Boolean(object.dstIsAgent) : false,
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      proto: isSet(object.proto) ? globalThis.String(object.proto) : "",
      srcPort: isSet(object.srcPort) ? globalThis.Number(object.srcPort) : 0,
      dstPort: isSet(object.dstPort) ? globalThis.Number(object.dstPort) : 0,
    };
  },

  toJSON(message: Packet): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.srcIp !== "") {
      obj.srcIp = message.srcIp;
    }
    if (message.dstIp !== "") {
      obj.dstIp = message.dstIp;
    }
    if (message.srcIsAgent !== false) {
      obj.srcIsAgent = message.srcIsAgent;
    }
    if (message.dstIsAgent !== false) {
      obj.dstIsAgent = message.dstIsAgent;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.proto !== "") {
      obj.proto = message.proto;
    }
    if (message.srcPort !== 0) {
      obj.srcPort = Math.round(message.srcPort);
    }
    if (message.dstPort !== 0) {
      obj.dstPort = Math.round(message.dstPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Packet>, I>>(base?: I): Packet {
    return Packet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Packet>, I>>(object: I): Packet {
    const message = createBasePacket();
    message.type = object.type ?? "";
    message.srcIp = object.srcIp ?? "";
    message.dstIp = object.dstIp ?? "";
    message.srcIsAgent = object.srcIsAgent ?? false;
    message.dstIsAgent = object.dstIsAgent ?? false;
    message.size = object.size ?? 0;
    message.proto = object.proto ?? "";
    message.srcPort = object.srcPort ?? 0;
    message.dstPort = object.dstPort ?? 0;
    return message;
  },
};

export interface AgentService {
  StreamPackets(request: Observable<DeepPartial<Packet>>, metadata?: grpc.Metadata): Promise<Empty>;
  Subscribe(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Observable<Packet>;
}

export class AgentServiceClientImpl implements AgentService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.StreamPackets = this.StreamPackets.bind(this);
    this.Subscribe = this.Subscribe.bind(this);
  }

  StreamPackets(request: Observable<DeepPartial<Packet>>, metadata?: grpc.Metadata): Promise<Empty> {
    throw new Error("ts-proto does not yet support client streaming!");
  }

  Subscribe(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Observable<Packet> {
    return this.rpc.invoke(AgentServiceSubscribeDesc, Empty.fromPartial(request), metadata);
  }
}

export const AgentServiceDesc = { serviceName: "packet.AgentService" };

export const AgentServiceSubscribeDesc: UnaryMethodDefinitionish = {
  methodName: "Subscribe",
  service: AgentServiceDesc,
  requestStream: false,
  responseStream: true,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Packet.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;
    streamingTransport?: grpc.TransportFactory;
    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;
      streamingTransport?: grpc.TransportFactory;
      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }

  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any> {
    const upStreamCodes = this.options.upStreamRetryCodes ?? [];
    const DEFAULT_TIMEOUT_TIME: number = 3_000;
    const request = { ..._request, ...methodDesc.requestType };
    const transport = this.options.streamingTransport ?? this.options.transport;
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Observable((observer) => {
      const upStream = () => {
        const client = grpc.invoke(methodDesc, {
          host: this.host,
          request,
          ...(transport !== undefined ? { transport } : {}),
          metadata: maybeCombinedMetadata ?? {},
          debug: this.options.debug ?? false,
          onMessage: (next) => observer.next(next),
          onEnd: (code: grpc.Code, message: string, trailers: grpc.Metadata) => {
            if (code === 0) {
              observer.complete();
            } else if (upStreamCodes.includes(code)) {
              setTimeout(upStream, DEFAULT_TIMEOUT_TIME);
            } else {
              const err = new Error(message) as any;
              err.code = code;
              err.metadata = trailers;
              observer.error(err);
            }
          },
        });
        observer.add(() => client.close());
      };
      upStream();
    }).pipe(share());
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
