// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v3.21.12
// source: packet.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

export const protobufPackage = "packet";

export interface Empty {
}

export interface Packet {
  type: string;
  srcIp: string;
  dstIp: string;
  srcIsAgent: boolean;
  dstIsAgent: boolean;
  size: number;
  proto: string;
  srcPort: number;
  dstPort: number;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty = {
  encode(_: Empty, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Empty {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBasePacket(): Packet {
  return {
    type: "",
    srcIp: "",
    dstIp: "",
    srcIsAgent: false,
    dstIsAgent: false,
    size: 0,
    proto: "",
    srcPort: 0,
    dstPort: 0,
  };
}

export const Packet = {
  encode(message: Packet, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.srcIp !== "") {
      writer.uint32(18).string(message.srcIp);
    }
    if (message.dstIp !== "") {
      writer.uint32(26).string(message.dstIp);
    }
    if (message.srcIsAgent !== false) {
      writer.uint32(32).bool(message.srcIsAgent);
    }
    if (message.dstIsAgent !== false) {
      writer.uint32(40).bool(message.dstIsAgent);
    }
    if (message.size !== 0) {
      writer.uint32(48).int32(message.size);
    }
    if (message.proto !== "") {
      writer.uint32(58).string(message.proto);
    }
    if (message.srcPort !== 0) {
      writer.uint32(64).int32(message.srcPort);
    }
    if (message.dstPort !== 0) {
      writer.uint32(72).int32(message.dstPort);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Packet {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.srcIp = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.dstIp = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.srcIsAgent = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.dstIsAgent = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.size = reader.int32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.proto = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.srcPort = reader.int32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.dstPort = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Packet {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      srcIp: isSet(object.srcIp) ? globalThis.String(object.srcIp) : "",
      dstIp: isSet(object.dstIp) ? globalThis.String(object.dstIp) : "",
      srcIsAgent: isSet(object.srcIsAgent) ? globalThis.Boolean(object.srcIsAgent) : false,
      dstIsAgent: isSet(object.dstIsAgent) ? globalThis.Boolean(object.dstIsAgent) : false,
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      proto: isSet(object.proto) ? globalThis.String(object.proto) : "",
      srcPort: isSet(object.srcPort) ? globalThis.Number(object.srcPort) : 0,
      dstPort: isSet(object.dstPort) ? globalThis.Number(object.dstPort) : 0,
    };
  },

  toJSON(message: Packet): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.srcIp !== "") {
      obj.srcIp = message.srcIp;
    }
    if (message.dstIp !== "") {
      obj.dstIp = message.dstIp;
    }
    if (message.srcIsAgent !== false) {
      obj.srcIsAgent = message.srcIsAgent;
    }
    if (message.dstIsAgent !== false) {
      obj.dstIsAgent = message.dstIsAgent;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.proto !== "") {
      obj.proto = message.proto;
    }
    if (message.srcPort !== 0) {
      obj.srcPort = Math.round(message.srcPort);
    }
    if (message.dstPort !== 0) {
      obj.dstPort = Math.round(message.dstPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Packet>, I>>(base?: I): Packet {
    return Packet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Packet>, I>>(object: I): Packet {
    const message = createBasePacket();
    message.type = object.type ?? "";
    message.srcIp = object.srcIp ?? "";
    message.dstIp = object.dstIp ?? "";
    message.srcIsAgent = object.srcIsAgent ?? false;
    message.dstIsAgent = object.dstIsAgent ?? false;
    message.size = object.size ?? 0;
    message.proto = object.proto ?? "";
    message.srcPort = object.srcPort ?? 0;
    message.dstPort = object.dstPort ?? 0;
    return message;
  },
};

export interface AgentService {
  StreamPackets(request: Observable<Packet>): Promise<Empty>;
  Subscribe(request: Empty): Observable<Packet>;
}

export const AgentServiceServiceName = "packet.AgentService";
export class AgentServiceClientImpl implements AgentService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AgentServiceServiceName;
    this.rpc = rpc;
    this.StreamPackets = this.StreamPackets.bind(this);
    this.Subscribe = this.Subscribe.bind(this);
  }
  StreamPackets(request: Observable<Packet>): Promise<Empty> {
    const data = request.pipe(map((request) => Packet.encode(request).finish()));
    const promise = this.rpc.clientStreamingRequest(this.service, "StreamPackets", data);
    return promise.then((data) => Empty.decode(_m0.Reader.create(data)));
  }

  Subscribe(request: Empty): Observable<Packet> {
    const data = Empty.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "Subscribe", data);
    return result.pipe(map((data) => Packet.decode(_m0.Reader.create(data))));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
