// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.31.1
// source: packet.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Observable } from "rxjs";
import { share } from "rxjs/operators";

export const protobufPackage = "packet";

export enum Protocol {
  UNKNOWN = 0,
  TCP = 1,
  UDP = 2,
  ICMP = 3,
  OTHER = 4,
  UNRECOGNIZED = -1,
}

export function protocolFromJSON(object: any): Protocol {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return Protocol.UNKNOWN;
    case 1:
    case "TCP":
      return Protocol.TCP;
    case 2:
    case "UDP":
      return Protocol.UDP;
    case 3:
    case "ICMP":
      return Protocol.ICMP;
    case 4:
    case "OTHER":
      return Protocol.OTHER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Protocol.UNRECOGNIZED;
  }
}

export function protocolToJSON(object: Protocol): string {
  switch (object) {
    case Protocol.UNKNOWN:
      return "UNKNOWN";
    case Protocol.TCP:
      return "TCP";
    case Protocol.UDP:
      return "UDP";
    case Protocol.ICMP:
      return "ICMP";
    case Protocol.OTHER:
      return "OTHER";
    case Protocol.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Empty {
}

export interface PacketBatch {
  packets: Packet[];
}

export interface Packet {
  srcIp: Uint8Array;
  dstIp: Uint8Array;
  srcIsAgent: boolean;
  dstIsAgent: boolean;
  size: number;
  proto: Protocol;
  srcPort: number;
  dstPort: number;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBasePacketBatch(): PacketBatch {
  return { packets: [] };
}

export const PacketBatch: MessageFns<PacketBatch> = {
  encode(message: PacketBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.packets) {
      Packet.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketBatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.packets.push(Packet.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketBatch {
    return {
      packets: globalThis.Array.isArray(object?.packets) ? object.packets.map((e: any) => Packet.fromJSON(e)) : [],
    };
  },

  toJSON(message: PacketBatch): unknown {
    const obj: any = {};
    if (message.packets?.length) {
      obj.packets = message.packets.map((e) => Packet.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PacketBatch>, I>>(base?: I): PacketBatch {
    return PacketBatch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PacketBatch>, I>>(object: I): PacketBatch {
    const message = createBasePacketBatch();
    message.packets = object.packets?.map((e) => Packet.fromPartial(e)) || [];
    return message;
  },
};

function createBasePacket(): Packet {
  return {
    srcIp: new Uint8Array(0),
    dstIp: new Uint8Array(0),
    srcIsAgent: false,
    dstIsAgent: false,
    size: 0,
    proto: 0,
    srcPort: 0,
    dstPort: 0,
  };
}

export const Packet: MessageFns<Packet> = {
  encode(message: Packet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.srcIp.length !== 0) {
      writer.uint32(10).bytes(message.srcIp);
    }
    if (message.dstIp.length !== 0) {
      writer.uint32(18).bytes(message.dstIp);
    }
    if (message.srcIsAgent !== false) {
      writer.uint32(24).bool(message.srcIsAgent);
    }
    if (message.dstIsAgent !== false) {
      writer.uint32(32).bool(message.dstIsAgent);
    }
    if (message.size !== 0) {
      writer.uint32(40).int32(message.size);
    }
    if (message.proto !== 0) {
      writer.uint32(48).int32(message.proto);
    }
    if (message.srcPort !== 0) {
      writer.uint32(56).int32(message.srcPort);
    }
    if (message.dstPort !== 0) {
      writer.uint32(64).int32(message.dstPort);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Packet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.srcIp = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dstIp = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.srcIsAgent = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dstIsAgent = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.proto = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.srcPort = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.dstPort = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Packet {
    return {
      srcIp: isSet(object.srcIp) ? bytesFromBase64(object.srcIp) : new Uint8Array(0),
      dstIp: isSet(object.dstIp) ? bytesFromBase64(object.dstIp) : new Uint8Array(0),
      srcIsAgent: isSet(object.srcIsAgent) ? globalThis.Boolean(object.srcIsAgent) : false,
      dstIsAgent: isSet(object.dstIsAgent) ? globalThis.Boolean(object.dstIsAgent) : false,
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      proto: isSet(object.proto) ? protocolFromJSON(object.proto) : 0,
      srcPort: isSet(object.srcPort) ? globalThis.Number(object.srcPort) : 0,
      dstPort: isSet(object.dstPort) ? globalThis.Number(object.dstPort) : 0,
    };
  },

  toJSON(message: Packet): unknown {
    const obj: any = {};
    if (message.srcIp.length !== 0) {
      obj.srcIp = base64FromBytes(message.srcIp);
    }
    if (message.dstIp.length !== 0) {
      obj.dstIp = base64FromBytes(message.dstIp);
    }
    if (message.srcIsAgent !== false) {
      obj.srcIsAgent = message.srcIsAgent;
    }
    if (message.dstIsAgent !== false) {
      obj.dstIsAgent = message.dstIsAgent;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.proto !== 0) {
      obj.proto = protocolToJSON(message.proto);
    }
    if (message.srcPort !== 0) {
      obj.srcPort = Math.round(message.srcPort);
    }
    if (message.dstPort !== 0) {
      obj.dstPort = Math.round(message.dstPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Packet>, I>>(base?: I): Packet {
    return Packet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Packet>, I>>(object: I): Packet {
    const message = createBasePacket();
    message.srcIp = object.srcIp ?? new Uint8Array(0);
    message.dstIp = object.dstIp ?? new Uint8Array(0);
    message.srcIsAgent = object.srcIsAgent ?? false;
    message.dstIsAgent = object.dstIsAgent ?? false;
    message.size = object.size ?? 0;
    message.proto = object.proto ?? 0;
    message.srcPort = object.srcPort ?? 0;
    message.dstPort = object.dstPort ?? 0;
    return message;
  },
};

export interface AgentService {
  StreamPackets(request: Observable<DeepPartial<PacketBatch>>, metadata?: grpc.Metadata): Promise<Empty>;
  Subscribe(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Observable<PacketBatch>;
}

export class AgentServiceClientImpl implements AgentService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.StreamPackets = this.StreamPackets.bind(this);
    this.Subscribe = this.Subscribe.bind(this);
  }

  StreamPackets(request: Observable<DeepPartial<PacketBatch>>, metadata?: grpc.Metadata): Promise<Empty> {
    throw new Error("ts-proto does not yet support client streaming!");
  }

  Subscribe(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Observable<PacketBatch> {
    return this.rpc.invoke(AgentServiceSubscribeDesc, Empty.fromPartial(request), metadata);
  }
}

export const AgentServiceDesc = { serviceName: "packet.AgentService" };

export const AgentServiceSubscribeDesc: UnaryMethodDefinitionish = {
  methodName: "Subscribe",
  service: AgentServiceDesc,
  requestStream: false,
  responseStream: true,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = PacketBatch.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;
    streamingTransport?: grpc.TransportFactory;
    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;
      streamingTransport?: grpc.TransportFactory;
      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }

  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any> {
    const upStreamCodes = this.options.upStreamRetryCodes ?? [];
    const DEFAULT_TIMEOUT_TIME: number = 3_000;
    const request = { ..._request, ...methodDesc.requestType };
    const transport = this.options.streamingTransport ?? this.options.transport;
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Observable((observer) => {
      const upStream = () => {
        const client = grpc.invoke(methodDesc, {
          host: this.host,
          request,
          ...(transport !== undefined ? { transport } : {}),
          metadata: maybeCombinedMetadata ?? {},
          debug: this.options.debug ?? false,
          onMessage: (next) => observer.next(next),
          onEnd: (code: grpc.Code, message: string, trailers: grpc.Metadata) => {
            if (code === 0) {
              observer.complete();
            } else if (upStreamCodes.includes(code)) {
              setTimeout(upStream, DEFAULT_TIMEOUT_TIME);
            } else {
              const err = new Error(message) as any;
              err.code = code;
              err.metadata = trailers;
              observer.error(err);
            }
          },
        });
        observer.add(() => client.close());
      };
      upStream();
    }).pipe(share());
  }
}

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
